pipeline {
  agent any

  stages {
    stage ('Cleanup Working Directory') {
      steps {
        script {
          cleanWs()
        }
      }
    }

    stage ('Trivy File Scan') {
      steps {
        sh "trivy fs --format table -o fs.html ."         
      }
    }
  }
}